version: '2'

services:
  web:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: finxi_api
    volumes:
      - .:/app
    ports:
      - "8000:8000"
